# Generated by Django 4.2.6 on 2023-11-08 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customuser', to_field='username'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='play_points',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customuser', to_field='username'),
        ),
        migrations.CreateModel(
            name='TimeEntryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.TimeField()),
                ('A', models.IntegerField()),
                ('B', models.IntegerField()),
                ('C', models.IntegerField()),
                ('D', models.IntegerField()),
                ('E', models.IntegerField()),
                ('F', models.IntegerField()),
                ('G', models.IntegerField()),
                ('H', models.IntegerField()),
                ('I', models.IntegerField()),
                ('J', models.IntegerField()),
                ('K', models.IntegerField()),
                ('L', models.IntegerField()),
                ('M', models.IntegerField()),
                ('N', models.IntegerField()),
                ('O', models.IntegerField()),
                ('P', models.IntegerField()),
                ('Q', models.IntegerField()),
                ('R', models.IntegerField()),
                ('S', models.IntegerField()),
                ('T', models.IntegerField()),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='api.datemodel')),
            ],
        ),
    ]
