# Generated by Django 4.2.6 on 2023-12-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_admin_remove_useractivity_user_delete_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='credit',
            field=models.IntegerField(default=5000),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_block',
            field=models.BooleanField(default=False),
        ),
    ]
