# Generated by Django 4.2.6 on 2023-12-13 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_timeentrymodel_a_alter_timeentrymodel_b_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TSN',
            fields=[
                ('tsn_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('gamedate_time', models.DateTimeField()),
                ('playedpoints', models.IntegerField()),
                ('slipdatetime', models.DateTimeField()),
                ('cancel', models.BooleanField(default=False)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.transaction')),
            ],
            options={
                'ordering': ['gamedate_time'],
            },
        ),
        migrations.CreateModel(
            name='UserGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T')], max_length=1)),
                ('number', models.CharField(max_length=2)),
                ('Playedpoints', models.IntegerField()),
                ('tsn_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_games', to='api.tsn')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customuser')),
            ],
        ),
    ]
