# Generated by Django 4.2.6 on 2023-12-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_transaction_tsn_usergame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergame',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
