# Generated by Django 4.1.2 on 2023-12-19 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_earn_point_earnpoint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Win_Percent',
        ),
    ]
